version: '2.2'
services:
  elastic-main:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./eldata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  
  # https://www.elastic.co/guide/en/kibana/current/docker.html
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    environment:
      - ELASTICSEARCH_HOSTS=["http://elastic-main:9200"]
    ports:
      - 5601:5601
    depends_on:
      - elastic-main
   
